### ISSUE TITLE
export: not an identifier: 192.168.1.67:0.0

### ISSUE THREAD

**Issue by zer0mania** [Gymxo/Java-gui-through-ssh#2]
#                                                
XII:~ root# export DISPLAY=192.168.1.67:0.0
XII:~ root# export $DISPLAY
export: not an identifier: 192.168.1.67:0.0
XII:~ root#

**Comment by ScattyNatalie** [comment]
It would be echo $DISPLAY

**Comment by zer0mania** [comment]
thx
